-- Data Sources
-- https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
-- https://en.wikipedia.org/wiki/List_of_UTC_offsets

MERGE dbo.TimeZone AS TARGET
USING (VALUES               
              -- America
              ('America/Adak',                     'W', '-10:00', -600, '-09:00', -540, 'HST',  'HDT'),
              ('America/Anchorage',                'V', '-09:00', -540, '-08:00', -480, 'AKST', 'AKDT'),
              ('America/Anguilla',                 'Q', '-04:00', -240, NULL,     NULL, 'AST',  NULL),
              ('American/Antigua',                 'Q', '-04:00', -240, NULL,     NULL, 'AST',  NULL),
              ('America/Araguaina',                'P', '-03:00', -180, NULL,     NULL, '-03',  NULL),
              ('America/Argentina/Buenos Aires',   'P', '-03:00', -180, NULL,     NULL, '-03',  NULL),
              ('America/Argentina/Catamarca',      'P', '-03:00', -180, NULL,     NULL, '-03',  NULL),
              ('America/Argentina/Cordoba',        'P', '-03:00', -180, NULL,     NULL, '-03',  NULL),
              ('America/Argentina/Jujuy',          'P', '-03:00', -180, NULL,     NULL, '-03',  NULL),
              ('America/Argentina/La Rioja',       'P', '-03:00', -180, NULL,     NULL, '-03',  NULL),
              ('America/Argentina/Mendoza',        'P', '-03:00', -180, NULL,     NULL, '-03',  NULL),
              ('America/Argentina/Rio Gallegos',   'P', '-03:00', -180, NULL,     NULL, '-03',  NULL),
              ('America/Argentina/Salta',          'P', '-03:00', -180, NULL,     NULL, '-03',  NULL),
              ('America/Argentina/San Juan',       'P', '-03:00', -180, NULL,     NULL, '-03',  NULL),
              ('America/Argentina/San Luis',       'P', '-03:00', -180, NULL,     NULL, '-03',  NULL),
              ('America/Argentina/Tucuman',        'P', '-03:00', -180, NULL,     NULL, '-03',  NULL),
              ('America/Argentina/Ushuaia',        'P', '-03:00', -180, NULL,     NULL, '-03',  NULL),
              ('America/Aruba',                    'Q', '-04:00', -240, NULL,     NULL, 'AST',  NULL),
              ('America/Asuncion',                 'Q', '-04:00', -240, NULL,     NULL, '-04',  '-03'),
              ('America/Atikokan',                 'R', '-05:00', -300, NULL,     NULL, 'EST',  NULL),
              ('America/Atka',                     'W', '-10:00', -600, '-09:00', -540, 'HST',  'HDT'),
              ('America/Bahia',                    'P', '-03:00', -180, NULL,     NULL, '-03',  NULL),
              ('America/Bahia Banderas',           'S', '-06:00', -360, NULL,     NULL, 'CST',  NULL),
              ('America/Barbados',                 'Q', '-04:00', -240, NULL,     NULL, 'AST',  NULL),
              ('America/Belem',                    'P', '-03:00', -180, NULL,     NULL, '-03',  NULL),
              ('America/Belize',                   'S', '-06:00', -360, NULL,     NULL, 'CST',  NULL),
              ('America/Blanc-Sablon',             'Q', '-04:00', -240, NULL,     NULL, 'AST',  NULL),
              ('America/Boa Vista',                'Q', '-04:00', -240, NULL,     NULL, '-04',  NULL),
              ('America/Bogota',                   'R', '-05:00', -300, NULL,     NULL, '-05',  NULL),
              ('America/Boise',                    'T', '-07:00', -420, '-06:00', -360, 'MST',  'MDT'),
              ('America/Cambridge Bay',            'T', '-07:00', -420, '-06:00', -360, 'MST',  'MDT'),
              ('America/Campo Grande',             'Q', '-04:00', -240, NULL,     NULL, '-04',  NULL),
              ('America/Cancun',                   'R', '-05:00', -300, NULL,     NULL, 'EST',  NULL),
              ('America/Caracas',                  'Q', '-04:00', -240, NULL,     NULL, '-04',  NULL),
              ('America/Cayenne',                  'P', '-03:00', -180, NULL,     NULL, '-03',  NULL),
              ('America/Cayman',                   'R', '-05:00', -300, NULL,     NULL, 'EST',  NULL),
              ('America/Chicago',                  'S', '-06:00', -360, '-05:00', -300, 'CST',  'CDT'),
              ('America/Chihuahua',                'S', '-06:00', -360, NULL,     NULL, 'CST',  NULL),
              ('America/Ciudad Juarez',            'T', '-07:00', -420, '-06:00', -360, 'MST',  'MDT'),
              ('America/Coral Harbour',            'R', '-05:00', -300, NULL,     NULL, 'EST',  NULL),
              ('America/Costa Rica',               'S', '-06:00', -360, NULL,     NULL, 'CST',  NULL),
              ('America/Cuiaba',                   'Q', '-04:00', -240, NULL,     NULL, '-04',  NULL),
              ('America/Curacao',                  'Q', '-04:00', -240, NULL,     NULL, 'AST',  NULL),
              ('America/Danmarkshavn',             'Z', '-00:00', 0,    NULL,     NULL, 'GMT',  NULL),
              ('America/Dawson',                   'T', '-07:00', -420, NULL,     NULL, 'MST',  NULL),
              ('America/Dawson Creek',             'T', '-07:00', -420, NULL,     NULL, 'MST',  NULL),
              ('America/Denver',                   'T', '-07:00', -420, '-06:00', -360, 'MST',  'MDT'),
              ('America/Detroit',                  'R', '-05:00', -300, '-04:00', -240, 'EST',  'EDT'),
              ('America/Dominica',                 'Q', '-04:00', -240, NULL,     NULL, 'AST',  NULL),
              ('America/Edmonton',                 'T', '-07:00', -420, '-06:00', -360, 'MST',  'MDT'),
              ('America/Eirunepe',                 'R', '-05:00', -300, NULL,     NULL, '-05',  NULL),
              ('America/El Salvador',              'S', '-06:00', -360, NULL,     NULL, 'CST',  NULL),
              ('America/Fort Nelson',              'T', '-07:00', -420, NULL,     NULL, 'MST',  NULL),
              ('America/Fortaleza',                'P', '-03:00', -180, NULL,     NULL, '-03',  NULL),
              ('America/Glace Bay',                'Q', '-04:00', -240, '-03:00', -180, 'AST',  'ADT'),
              ('America/Goose Bay',                'Q', '-04:00', -240, '-03:00', -180, 'AST',  'ADT'),
              ('America/Grand Turk',               'R', '-05:00', -300, '-04:00', -240, 'EST',  'EDT'),
              ('America/Grenada',                  'Q', '-04:00', -240, NULL,     NULL, 'AST',  NULL),
              ('America/Guadeloupe',               'Q', '-04:00', -240, NULL,     NULL, 'AST',  NULL),
              ('America/Guatemala',                'S', '-06:00', -360, NULL,     NULL, 'CST',  NULL),
              ('America/Guayaquil',                'R', '-05:00', -300, NULL,     NULL, '-05',  NULL),
              ('America/Guyana',                   'Q', '-04:00', -240, NULL,     NULL, '-04',  NULL),
              ('America/Halifax',                  'Q', '-04:00', -240, '-03:00', -180, 'AST',  'ADT'),
              ('America/Havana',                   'S', '-06:00', -360, '-05:00', -300, 'CST',  'CDT'),
              ('America/Hermosillo',               'T', '-07:00', -420, NULL,     NULL, 'MST',  NULL),
              ('America/Indiana/Indianapolis',     'R', '-05:00', -300, '-04:00', -240, 'EST',  'EDT'),
              ('America/Indiana/Knox',             'S', '-06:00', -360, '-05:00', -300, 'CST',  'CDT'),
              ('America/Indiana/Marengo',          'R', '-05:00', -300, '-04:00', -240, 'EST',  'EDT'),
              ('America/Indiana/Petersburg',       'R', '-05:00', -300, '-04:00', -240, 'EST',  'EDT'),
              ('America/Indiana/Tell City',        'S', '-06:00', -360, '-05:00', -300, 'CST',  'CDT'),
              ('America/Indiana/Vevay',            'R', '-05:00', -300, '-04:00', -240, 'EST',  'EDT'),
              ('America/Indiana/Vincennes',        'R', '-05:00', -300, '-04:00', -240, 'EST',  'EDT'),
              ('America/Indiana/Winamac',          'R', '-05:00', -300, '-04:00', -240, 'EST',  'EDT'),
              ('America/Inuvik',                   'T', '-07:00', -420, '-06:00', -360, 'MST',  'MDT'),
              ('America/Iqaluit',                  'R', '-05:00', -300, '-04:00', -240, 'EST',  'EDT'),
              ('America/Jamaica',                  'R', '-05:00', -300, NULL,     NULL, 'EST',  NULL),
              ('America/Juneau',                   'V', '-09:00', -540, '-08:00', -480, 'AKST', 'AKDT'),
              ('America/Kentucky/Louisville',      'R', '-05:00', -300, '-04:00', -240, 'EST',  'EDT'),
              ('America/Kentucky/Monticello',      'R', '-05:00', -300, '-04:00', -240, 'EST',  'EDT'),
              ('America/Kralendijk',               'Q', '-04:00', -240, NULL,     NULL, 'AST',  NULL),
              ('America/La Paz',                   'Q', '-04:00', -240, NULL,     NULL, '-04',  NULL),
              ('America/Lima',                     'R', '-05:00', -300, NULL,     NULL, '-05',  NULL),
              ('America/Los Angeles',              'U', '-08:00', -480, '07:00',  -420, 'PST',  'PDT'),
              ('America/Lower Princes',            'Q', '-04:00', -240, NULL,     NULL, 'AST',  NULL),
              ('America/Maceio',                   'P', '-03:00', -180, NULL,     NULL, '-03',  NULL),
              ('America/Managua',                  'S', '-06:00', -360, NULL,     NULL, 'CST',  NULL),
              ('America/Manaus',                   'Q', '-04:00', -240, NULL,     NULL, '-04',  NULL),
              ('America/Marigot',                  'Q', '-04:00', -240, NULL,     NULL, 'AST',  NULL),
              ('America/Martinique',               'Q', '-04:00', -240, NULL,     NULL, 'AST',  NULL),
              ('America/Matamoros',                'S', '-06:00', -360, '-05:00', -300, 'CST',  'CDT'),
              ('America/Mazatlan',                 'T', '-07:00', -420, NULL,     NULL, 'MST',  NULL),
              ('America/Menominee',                'S', '-06:00', -360, '-05:00', -300, 'CST',  'CDT'),
              ('America/Merida',                   'S', '-06:00', -360, NULL,     NULL, 'CST',  NULL),
              ('America/Metlakatla',               'V', '-09:00', -540, '-08:00', -480, 'AKST', 'AKDT'),
              ('America/Mexico City',              'S', '-06:00', -360, NULL,     NULL, 'CST',  NULL),
              ('America/Miquelon',                 'P', '-03:00', -180, '-02:00', -120, '-03',  '-02'),
              ('America/Moncton',                  'Q', '-04:00', -240, '-03:00', -180, 'AST',  'ADT'),
              ('America/Monterrey',                'S', '-06:00', -360, NULL,     NULL, 'CST',  NULL),
              ('America/Montevideo',               'P', '-03:00', -180, NULL,     NULL, '-03',  NULL),
              ('America/Montreal',                 'R', '-05:00', -300, '-04:00', -240, 'EST',  'EDT'),
              ('America/Montserrat',               'Q', '-04:00', -240, NULL,     NULL, 'AST',  NULL),
              ('America/Nassau',                   'R', '-05:00', -300, '-04:00', -240, 'EST',  'EDT'),
              ('America/New York',                 'R', '-05:00', -300, '-04:00', -240, 'EST',  'EDT'),
              ('America/Nome',                     'V', '-09:00', -540, '-08:00', -480, 'AKST', 'AKDT'),
              ('America/Noronha',                  'O', '-02:00', -120, NULL,     NULL, '-02',  NULL),
              ('America/North Dakota/Beulah',      'S', '-06:00', -360, '-05:00', -300, 'CST',  'CDT'),
              ('America/North Dakota/Center',      'S', '-06:00', -360, '-05:00', -300, 'CST',  'CDT'),
              ('America/North Dakota/New Salem',   'S', '-06:00', -360, '-05:00', -300, 'CST',  'CDT'),
              ('America/Nuuk',                     'O', '-02:00', -120, NULL,     NULL, '-02',  NULL),
              ('America/Ojinaga',                  'S', '-06:00', -360, '-05:00', -300, 'CST',  'CDT'),
              ('America/Panama',                   'R', '-05:00', -300, NULL,     NULL, 'EST',  NULL),
              ('America/Paramaribo',               'P', '-03:00', -180, NULL,     NULL, '-03',  NULL),
              ('America/Phoenix',                  'T', '-07:00', -420, NULL,     NULL, 'MST',  NULL),
              ('America/Port-au-Prince',           'R', '-05:00', -300, '-04:00', -240, 'EST',  'EDT'),
              ('America/Port of Spain',            'Q', '-04:00', -240, NULL,     NULL, 'AST',  NULL),
              ('America/Porto Velho',              'Q', '-04:00', -240, NULL,     NULL, '-04',  NULL),
              ('America/Puerto Rico',              'Q', '-04:00', -240, NULL,     NULL, '-04',  NULL),
              ('America/Punta Arenas',             'P', '-03:00', -180, NULL,     NULL, '-03',  NULL),
              ('America/Rankin Inlet',             'S', '-06:00', -360, '-05:00', -300, 'CST',  'CDT'),
              ('America/Recife',                   'P', '-03:00', -180, NULL,     NULL, '-03',  NULL),
              ('America/Regina',                   'S', '-06:00', -360, NULL,     NULL, 'CST',  NULL),
              ('America/Resolute',                 'S', '-06:00', -360, '-05:00', -300, 'CST',  'CDT'),
              ('America/Rio Branco',               'R', '-05:00', -300, NULL,     NULL, '-05',  NULL),
              ('America/Santarem',                 'P', '-03:00', -180, NULL,     NULL, '-03',  NULL),
              ('America/Santiago',                 'Q', '-04:00', -240, '-03:00', -180, '-04',  '-03'),
              ('America/Santo Domingo',            'Q', '-04:00', -240, NULL,     NULL, 'AST',  NULL),
              ('America/Sao Paulo',                'P', '-03:00', -180, NULL,     NULL, '-03',  NULL),
              ('America/Scoresbysund',             'N', '-01:00', -60,  '+00:00', 0,    '-01', '+00'),
              ('America/Sitka',                    'V', '-09:00', -540, '-08:00', -480, 'AKST', 'AKDT'),
              ('America/St Barthelemy',            'Q', '-04:00', -240, NULL,     NULL, 'AST',  NULL),
              ('America/St Johns',                 'P', '-03:30', -210, '-02:30', -150, 'NST',  'NDT'),
              ('America/St Kitts',                 'Q', '-04:00', -240, NULL,     NULL, 'AST',  NULL),
              ('America/St Lucia',                 'Q', '-04:00', -240, NULL,     NULL, 'AST',  NULL),
              ('America/St Thomas',                'Q', '-04:00', -240, NULL,     NULL, 'AST',  NULL),
              ('America/St Vincent',               'Q', '-04:00', -240, NULL,     NULL, 'AST',  NULL),
              ('America/Swift Current',            'S', '-06:00', -360, NULL,     NULL, 'CST',  NULL),
              ('America/Tegucigalpa',              'S', '-06:00', -360, NULL,     NULL, 'CST',  NULL),
              ('America/Thule',                    'Q', '-04:00', -240, '-03:00', -180, 'AST',  'ADT'),
              ('America/Tijuana',                  'U', '-08:00', -480, '07:00',  -420, 'PST',  'PDT'),
              ('America/Toronto',                  'R', '-05:00', -300, '-04:00', -240, 'EST',  'EDT'),
              ('America/Tortola',                  'Q', '-04:00', -240, NULL,     NULL, 'AST',  NULL),
              ('America/Vancouver',                'U', '-08:00', -480, '07:00',  -420, 'PST',  'PDT'),
              ('America/Virgin',                   'Q', '-04:00', -240, NULL,     NULL, 'AST',  NULL),
              ('America/Whitehorse',               'T', '-07:00', -420, NULL,     NULL, 'MST',  NULL),
              ('America/Winnipeg',                 'S', '-06:00', -360, '-05:00', -300, 'CST',  'CDT'),
              ('America/Yakutat',                  'V', '-09:00', -540, '-08:00', -480, 'AKST', 'AKDT')
              
              )
AS SOURCE (TimeZoneId,
           UTCOffsetId,
           STDOffsetName,
           STDOffsetMinutes,
           DSTOffsetName,
           DSTOffsetMinutes,
           STDAbbreviation,
           DSTAbbreviation)
ON TARGET.TimeZoneId = SOURCE.TimeZoneId
WHEN MATCHED THEN UPDATE SET TARGET.UTCOffsetId      = SOURCE.UTCOffsetId,
                             TARGET.STDAbbreviation  = SOURCE.STDAbbreviation,
                             TARGET.STDOffsetName    = SOURCE.STDOffsetName,
                             TARGET.STDOffsetMinutes = SOURCE.STDOffsetMinutes,
                             TARGET.DSTAbbreviation  = SOURCE.DSTAbbreviation,
                             TARGET.DSTOffsetName    = SOURCE.DSTOffsetName,
                             TARGET.DSTOffsetMinutes = SOURCE.DSTOffsetMinutes
WHEN NOT MATCHED BY TARGET THEN INSERT (TimeZoneId,
                                        UTCOffsetId,
                                        STDAbbreviation,
                                        STDOffsetName,
                                        STDOffsetMinutes,
                                        DSTAbbreviation,
                                        DSTOffsetName,
                                        DSTOffsetMinutes)
                                VALUES (SOURCE.TimeZoneId,
                                        SOURCE.UTCOffsetId,
                                        SOURCE.STDAbbreviation,
                                        SOURCE.STDOffsetName,
                                        SOURCE.STDOffsetMinutes,
                                        SOURCE.DSTAbbreviation,
                                        SOURCE.DSTOffsetName,
                                        SOURCE.DSTOffsetMinutes)
WHEN NOT MATCHED BY SOURCE THEN DELETE;
GO