// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ConsoleApp1.Models;

/// <summary>
/// Represents a download associated with a engagement presentation.
/// </summary>
public partial class EngagementPresentationDownload
{
    /// <summary>
    /// Identifier of the EngagementPresentationDownload record.
    /// </summary>
    public int EngagementPresentationDownloadId { get; set; }

    /// <summary>
    /// Identifier of the associated engagement presentation.
    /// </summary>
    public int EngagementPresentationId { get; set; }

    public string DownloadName { get; set; }

    /// <summary>
    /// The link to the download.
    /// </summary>
    public string DownloadUrl { get; set; }

    public virtual EngagementPresentation EngagementPresentation { get; set; }
}