// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ConsoleApp1.Models;

/// <summary>
/// Represents a status of a engagement.
/// </summary>
public partial class EngagementStatus
{
    /// <summary>
    /// The identifier of the engagement status record.
    /// </summary>
    public int EngagementStatusId { get; set; }

    /// <summary>
    /// The name of the engagement status.
    /// </summary>
    public string EngagementStatusName { get; set; }

    public virtual ICollection<Engagement> Engagements { get; set; } = new List<Engagement>();
}