// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ConsoleApp1.Models;

/// <summary>
/// Represents a speaker presenting an engagement presentation.
/// </summary>
public partial class EngagementPresentationSpeaker
{
    /// <summary>
    /// Identifier of the EngagementPresentationSpeaker record.
    /// </summary>
    public int EngagementPresentationSpeakerId { get; set; }

    /// <summary>
    /// Identifier of the engagement presentation.
    /// </summary>
    public int EngagementPresentationId { get; set; }

    /// <summary>
    /// Identifier of the assigned speaker.
    /// </summary>
    public int SpeakerId { get; set; }

    /// <summary>
    /// Flag indicating whether the speaker is the primary speaker for the engagement presentation.
    /// </summary>
    public bool IsPrimarySpeaker { get; set; }

    public virtual EngagementPresentation EngagementPresentation { get; set; }

    public virtual Speaker Speaker { get; set; }
}