// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ConsoleApp1.Models;

/// <summary>
/// Represents a learning objective of a presentation.
/// </summary>
public partial class LearningObjective
{
    /// <summary>
    /// The identifier of the learning objective record.
    /// </summary>
    public int LearningObjectiveId { get; set; }

    /// <summary>
    /// The identifier of the associated presentation (text) record.
    /// </summary>
    public int PresentationTextId { get; set; }

    /// <summary>
    /// The text of the learning objective.
    /// </summary>
    public string LearningObjectiveText { get; set; }

    /// <summary>
    /// The sorting order of the learning objective.
    /// </summary>
    public int SortOrder { get; set; }

    public virtual PresentationText PresentationText { get; set; }
}