// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ConsoleApp1.Models;

/// <summary>
/// Represents a type of a speaker award.
/// </summary>
public partial class SpeakerAwardType
{
    /// <summary>
    /// The identifier of the speaker award type record.
    /// </summary>
    public int SpeakerAwardTypeId { get; set; }

    /// <summary>
    /// The name of the speaker award type name.
    /// </summary>
    public string SpeakerAwardTypeName { get; set; }

    /// <summary>
    /// Flag indicating whether the speaker award has categories.
    /// </summary>
    public bool HasCategories { get; set; }

    /// <summary>
    /// Flag indicating whether the speaker award has award year.
    /// </summary>
    public bool HasAwardYears { get; set; }

    public virtual ICollection<SpeakerAward> SpeakerAwards { get; set; } = new List<SpeakerAward>();
}