// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TaleLearnCode.SpeakerToolkit.Models;

/// <summary>
/// Represents the association between a engagement and a tag.
/// </summary>
public partial class EngagementTag
{
    /// <summary>
    /// The identifier of the engagement/tag record.
    /// </summary>
    public int EngagementTagId { get; set; }

    /// <summary>
    /// Identifier of the associated engagement.
    /// </summary>
    public int EngagementId { get; set; }

    /// <summary>
    /// Identifier of the associated tag.
    /// </summary>
    public int TagId { get; set; }

    public virtual Engagement Engagement { get; set; }

    public virtual Tag Tag { get; set; }
}