// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TaleLearnCode.SpeakerToolkit.Models;

/// <summary>
/// Represents a type of engagement.
/// </summary>
public partial class EngagementType
{
    /// <summary>
    /// The identifier of the engagement type record.
    /// </summary>
    public int EngagementTypeId { get; set; }

    /// <summary>
    /// The name of the engagement type.
    /// </summary>
    public string EngagementTypeName { get; set; }

    public virtual ICollection<Engagement> Engagements { get; set; } = new List<Engagement>();
}