// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TaleLearnCode.SpeakerToolkit.Models;

/// <summary>
/// Represents the association between a presentation and a tag.
/// </summary>
public partial class PresentationTag
{
    /// <summary>
    /// The identifier of the presentation/tag record.
    /// </summary>
    public int PresentationTagId { get; set; }

    /// <summary>
    /// Identifier of the associated presentation.
    /// </summary>
    public int PresentationId { get; set; }

    /// <summary>
    /// Identifier of the associated tag.
    /// </summary>
    public int TagId { get; set; }

    public virtual Presentation Presentation { get; set; }

    public virtual Tag Tag { get; set; }
}