// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TaleLearnCode.SpeakerToolkit.Models;

/// <summary>
/// Links two related presentations togethers.
/// </summary>
public partial class PresentationRelated
{
    /// <summary>
    /// The identifier of the related presentation object.
    /// </summary>
    public int PresentationRelatedId { get; set; }

    /// <summary>
    /// The identifier of the primary presentation.
    /// </summary>
    public int PrimaryPresentationId { get; set; }

    /// <summary>
    /// The identifier of the related presentation.
    /// </summary>
    public int RelatedPresentationId { get; set; }

    /// <summary>
    /// The sorting order of the related presentation.
    /// </summary>
    public int SortOrder { get; set; }

    public virtual Presentation PrimaryPresentation { get; set; }

    public virtual Presentation RelatedPresentation { get; set; }
}