// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TaleLearnCode.SpeakerToolkit.Models;

/// <summary>
/// Represents a link to a website/social media profile.
/// </summary>
public partial class SpeakerLink
{
    /// <summary>
    /// The identifier of the link record.
    /// </summary>
    public int SpeakerLinkId { get; set; }

    /// <summary>
    /// The identifier of the associated speaker.
    /// </summary>
    public int SpeakerId { get; set; }

    /// <summary>
    /// The type of link being represented.
    /// </summary>
    public string LinkType { get; set; }

    /// <summary>
    /// The URL of the link.
    /// </summary>
    public string LinkUrl { get; set; }

    public virtual Speaker Speaker { get; set; }
}