// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TaleLearnCode.SpeakerToolkit.Models;

/// <summary>
/// Represents a label attached to a presentation.
/// </summary>
public partial class Tag
{
    /// <summary>
    /// The identifier of the tag record.
    /// </summary>
    public int TagId { get; set; }

    /// <summary>
    /// The name of the tag.
    /// </summary>
    public string TagName { get; set; }

    public virtual ICollection<EngagementTag> EngagementTags { get; set; } = new List<EngagementTag>();

    public virtual ICollection<PresentationTag> PresentationTags { get; set; } = new List<PresentationTag>();
}